import Link from 'next/link'
import TopNav from '@/components/TopNav'

export const metadata = {
  title: 'Privacy — Personal OS',
  description: 'Privacy policy for the Personal OS dashboard.',
}

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#050d1c]">
      <TopNav />
      <main className="app-page-top px-3 pb-12 md:px-5 max-w-3xl mx-auto">
        <div className="mb-6">
          <div className="flex items-center gap-2 mb-2">
            <span className="text-[10px] text-zinc-600 tracking-widest">// </span>
            <span className="text-[10px] text-zinc-500 tracking-[0.2em]">PRIVACY</span>
          </div>
          <div className="flex items-center justify-between">
            <h1 className="text-base text-zinc-100">Privacy Policy</h1>
            <Link
              href="/"
              className="text-[10px] text-zinc-600 hover:text-zinc-300 tracking-wider transition-colors"
            >
              ← HOME
            </Link>
          </div>
          <p className="text-[10px] text-zinc-600 tracking-wider mt-2">Last updated: 27 May 2026</p>
        </div>

        <article className="prose-custom text-sm text-zinc-300 leading-relaxed space-y-5">
          <Section title="Who runs this">
            <p>
              Personal OS is a self-hosted personal dashboard operated by a single individual,
              Bryan Schippers, for his own use. It is not a product offered to other users.
              Contact:{' '}
              <a href="mailto:bryanschippers.bs@gmail.com" className="text-accent hover:underline">
                bryanschippers.bs@gmail.com
              </a>.
            </p>
          </Section>

          <Section title="What data is processed">
            <ul className="list-disc list-inside space-y-1 text-zinc-400">
              <li>Authentication credentials (email and password hash via Supabase Auth)</li>
              <li>Journal entries written or dictated by the account holder</li>
              <li>Todos and goals created by the account holder</li>
              <li>Bank transactions retrieved from Rabobank via Enable Banking, with the account holder&rsquo;s explicit consent</li>
              <li>Insights generated by the Anthropic Claude API based on the above</li>
            </ul>
          </Section>

          <Section title="Where data is stored">
            <p>
              All personal data lives in a Supabase Postgres database under the account holder&rsquo;s
              own Supabase project, hosted in the EU. Row-level security ensures the database
              row owner is the only party that can read or modify rows. Authentication cookies
              are stored in the user&rsquo;s browser only.
            </p>
          </Section>

          <Section title="Third parties">
            <ul className="list-disc list-inside space-y-1 text-zinc-400">
              <li>
                <strong className="text-zinc-300">Supabase</strong> — database and authentication
                host
              </li>
              <li>
                <strong className="text-zinc-300">Vercel</strong> — application hosting
              </li>
              <li>
                <strong className="text-zinc-300">Enable Banking</strong> — PSD2 account
                information service for retrieving Rabobank transactions
              </li>
              <li>
                <strong className="text-zinc-300">Anthropic</strong> — API used to generate
                weekly insights from journal and transaction summaries
              </li>
            </ul>
            <p className="mt-2">
              No data is sold or shared with any other party. There are no analytics, tracking
              pixels, or advertising integrations.
            </p>
          </Section>

          <Section title="Bank data (PSD2)">
            <p>
              Bank account information is accessed only after the account holder grants explicit
              consent through Enable Banking&rsquo;s authorization flow. Consent is granted for a
              limited period (up to 180 days) and can be revoked at any time directly with the
              bank or by deleting the application from Enable Banking. Only read access is used —
              the application never initiates payments or modifies the bank account.
            </p>
          </Section>

          <Section title="Retention and deletion">
            <p>
              Data is retained until the account holder deletes it manually or terminates the
              underlying Supabase project. There is no automated purge.
            </p>
          </Section>

          <Section title="Changes">
            <p>
              This policy may be updated as the project evolves. Material changes will be dated
              at the top of this page.
            </p>
          </Section>
        </article>
      </main>
    </div>
  )
}

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section>
      <h2 className="text-[11px] text-zinc-500 tracking-[0.2em] uppercase mb-2">{title}</h2>
      <div className="text-sm text-zinc-300 leading-relaxed">{children}</div>
    </section>
  )
}
